#!/bin/sh

# NOTE;  If you are using cygwin on Windows, the colon below 
#        should be a semi-colon
CLASSPATH=".;lib/collections.jar;lib/xerces.jar;lib/MRJToolkitStubs.jar;lib/logicrypto.jar"
export CLASSPATH


export CLASSPATH
PATH=$PATH:../core/bin
export PATH

java com.limegroup.gnutella.Main
