#!/bin/sh

# NOTE;  If you are using cygwin on Windows, the colon below 
#        should be a semi-colon
CLASSPATH=".;../lib/jars/collections.jar;../lib/jars/xerces.jar;../lib/jars/MRJToolkitStubs.jar;../lib/jars/logicrypto.jar"
export CLASSPATH


export CLASSPATH
PATH=$PATH:../core/bin
export PATH

java com.limegroup.gnutella.Main
