/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limegroup_gnutella_util_SystemUtils */

#ifndef _Included_com_limegroup_gnutella_util_SystemUtils
#define _Included_com_limegroup_gnutella_util_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limegroup_gnutella_util_SystemUtils
 * Method:    idleTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_limegroup_gnutella_util_SystemUtils_idleTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
