
// Microsoft Visual Studio compiles this Windows native code into SystemUtilities.dll
// LimeWire uses these functions from the class com.limegroup.gnutella.util.SystemUtils

// Headers generated by Java for functions Java code can call
#ifndef _Included_com_limegroup_gnutella_util_SystemUtils_Registry
#define _Included_com_limegroup_gnutella_util_SystemUtils_Registry
#ifdef __cplusplus
extern "C" {
#endif

	// Functions in Registry.cpp
	JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_util_SystemUtils_registryReadNumberNative(JNIEnv *e, jclass c, jstring root, jstring path, jstring name);
	JNIEXPORT jstring JNICALL Java_com_limegroup_gnutella_util_SystemUtils_registryReadTextNative(JNIEnv *e, jclass c, jstring root, jstring path, jstring name);
	JNIEXPORT jboolean JNICALL Java_com_limegroup_gnutella_util_SystemUtils_registryWriteNumberNative(JNIEnv *e, jclass c, jstring root, jstring path, jstring name, jint value);
	JNIEXPORT jboolean JNICALL Java_com_limegroup_gnutella_util_SystemUtils_registryWriteTextNative(JNIEnv *e, jclass c, jstring root, jstring path, jstring name, jstring value);
	JNIEXPORT jboolean JNICALL Java_com_limegroup_gnutella_util_SystemUtils_registryDeleteNative(JNIEnv *e, jclass c, jstring root, jstring path, jstring name);

#ifdef __cplusplus
}
#endif
#endif

// Wraps a registry key, taking care of closing it
class CRegistry {
public:

	// The handle to the registry key
	HKEY key;

	// Open a registry key and store its handle in this object
	bool Open(LPCTSTR root, LPCTSTR path, DWORD access);

	// Make a new local CRegistry object, and delete it when it goes out of scope
	CRegistry() { key = NULL; }
	~CRegistry() { if (key) RegCloseKey(key); key = NULL; }
};

// Functions in Registry.cpp
int RegistryReadNumber(LPCTSTR root, LPCTSTR path, LPCTSTR name);
CString RegistryReadText(LPCTSTR root, LPCTSTR path, LPCTSTR name);
bool RegistryWriteNumber(LPCTSTR root, LPCTSTR path, LPCTSTR name, int value);
bool RegistryWriteText(LPCTSTR root, LPCTSTR path, LPCTSTR name, LPCTSTR value);
bool RegistryDelete(LPCTSTR root, LPCTSTR path, LPCTSTR name);
HKEY RegistryName(LPCTSTR name);
