
// Microsoft Visual Studio compiles this Windows native code into SystemUtilities.dll
// LimeWire uses these functions from the class com.limegroup.gnutella.util.SystemUtils

// Window messages
#define MESSAGE_TRAY (WM_APP + 1)

// Headers generated by Java for functions Java code can call
#ifndef _Included_com_limegroup_gnutella_util_SystemUtils_Tray
#define _Included_com_limegroup_gnutella_util_SystemUtils_Tray
#ifdef __cplusplus
extern "C" {
#endif

	// Functions in Tray.cpp
	JNIEXPORT jboolean JNICALL Java_com_limegroup_gnutella_util_SystemUtils_addTrayIconNative(JNIEnv *e, jclass c, jstring icon, jstring tip);
	JNIEXPORT jboolean JNICALL Java_com_limegroup_gnutella_util_SystemUtils_removeTrayIconNative(JNIEnv *e, jclass c);

#ifdef __cplusplus
}
#endif
#endif

// Functions in Tray.cpp
bool TrayAdd(JNIEnv *e, jclass c, LPCTSTR icon, LPCTSTR tip);
LRESULT CALLBACK WindowProcedure(HWND window, UINT message, WPARAM wparam, LPARAM lparam);
bool TrayRemove();
