package org.limewire.xmpp.client;

import org.jivesoftware.smack.*;
import org.jivesoftware.smack.packet.Presence;
import org.jivesoftware.smackx.ServiceDiscoveryManager;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import java.awt.*;
import java.util.Collection;
import java.util.Enumeration;

public class BuddyList {
    private JPanel myPanel;
    private JTree tree1;
    private DefaultMutableTreeNode root = new DefaultMutableTreeNode();

    public static void create(XMPPConnection connection) {
        JFrame frame = new JFrame("BuddyList");
        frame.setContentPane(new BuddyList(connection).myPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public BuddyList(final XMPPConnection connection) {
        $$$setupUI$$$();
        new Thread(new Runnable() {
            public void run() {
                getRoster(connection);
            }
        }).start();
    }

    private void getRoster(XMPPConnection connection) {

        ServiceDiscoveryManager serviceDiscoveryManager = ServiceDiscoveryManager.getInstanceFor(connection);

        Roster roster = connection.getRoster();
        roster.addRosterListener(new RosterListenerImpl(connection));

        /*HashSet<String> limewireClients = new HashSet<String>();
        for (RosterEntry rosterEntry : roster.getEntries()) {
            root.add(new DefaultMutableTreeNode(rosterEntry.getName()));
            tree1.updateUI();
            Iterator<Presence> presences = roster.getPresences(rosterEntry.getUser());
            while (presences.hasNext()) {
                Presence presence = presences.next();
                try {
                    if (serviceDiscoveryManager.discoverInfo(presence.getFrom()).containsFeature("http://www.limewire.org/")) {
                        limewireClients.add(presence.getFrom());
                        System.out.println("found lw client: " + presence.getFrom());
                    }
                } catch (XMPPException exception) {
                    //exception.printStackTrace();
                }
            }
        }*/
    }

    private void createUIComponents() {
        tree1 = new JTree(root);
        tree1.setToggleClickCount(1);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        myPanel = new JPanel();
        myPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        myPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(tree1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myPanel;
    }

    private class RosterListenerImpl implements RosterListener {
        private final XMPPConnection connection;

        public RosterListenerImpl(XMPPConnection connection) {
            this.connection = connection;
        }

        public void entriesAdded(Collection<String> strings) {
            //To change body of implemented methods use File | Settings | File Templates.
        }

        public void entriesUpdated(Collection<String> strings) {
            //To change body of implemented methods use File | Settings | File Templates.
        }

        public void entriesDeleted(Collection<String> strings) {
            //To change body of implemented methods use File | Settings | File Templates.
        }

        public void presenceChanged(Presence presence) {
            Roster roster = connection.getRoster();
            if (presence.getType() == Presence.Type.available) {
                RosterEntry entry = roster.getEntry(presence.getFrom());
                String name = entry.getName();
                if (name == null || name.trim().length() == 0) {
                    name = presence.getFrom();
                }
                root.add(new DefaultMutableTreeNode(name));
                tree1.updateUI();
                try {
                    if (ServiceDiscoveryManager.getInstanceFor(connection).discoverInfo(presence.getFrom()).containsFeature("http://www.limewire.org/")) {
                        System.out.println("found lw client: " + presence.getFrom());
                    }
                } catch (XMPPException exception) {
                    //exception.printStackTrace();
                }
            } else if (presence.getType() == Presence.Type.unavailable) {
                Enumeration children = root.children();
                while (children.hasMoreElements()) {
                    RosterEntry entry = roster.getEntry(presence.getFrom());
                    String name = entry.getName();
                    if (name == null || name.trim().length() == 0) {
                        name = presence.getFrom();
                    }
                    DefaultMutableTreeNode mutableTreeNode = (DefaultMutableTreeNode) children.nextElement();
                    String treeNodeName = (String) mutableTreeNode.getUserObject();
                    if (name.equals(treeNodeName)) {
                        root.remove(mutableTreeNode);
                    }
                }
            }
        }
    }
}
