/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limegroup_gnutella_util_NativeLauncher */

#ifndef _Included_com_limegroup_gnutella_util_NativeLauncher
#define _Included_com_limegroup_gnutella_util_NativeLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limegroup_gnutella_util_NativeLauncher
 * Method:    nativeLaunchFileWindows
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_util_NativeLauncher_nativeLaunchFileWindows
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
