package com.limegroup.gnutella.gui.search;

import java.util.List;

import junit.framework.TestCase;

public class ConvertToLimeXMLTest extends TestCase {
    
    public void testTrack() throws Exception {
        List<ConvertToLimeXML.Item> xmls = new ConvertToLimeXML().convertToItemsFromTrack(TRACK_TEST);
        System.out.println(xmls);
    }
    
    public void testAlbum() throws Exception {
        List<ConvertToLimeXML.Item> xmls = new ConvertToLimeXML().convertToItemsFromAlbum(ALBUM_TEST);
        System.out.println(xmls);
    }
    
    final static String TRACK_TEST;
    static {
        String s = "";
        s += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        s += "<response>\n";
        s += "\n";
        s += "<lst name=\"responseHeader\">\n";
        s += " <int name=\"status\">0</int>\n";
        s += " <int name=\"QTime\">0</int>\n";
        s += " <lst name=\"params\">\n";
        s += "  <str name=\"rows\">10</str>\n";
        s += "  <str name=\"start\">0</str>\n";
        s += "\n";
        s += "  <str name=\"indent\">on</str>\n";
        s += "  <str name=\"q\">love</str>\n";
        s += "  <str name=\"version\">2.2</str>\n";
        s += " </lst>\n";
        s += "</lst>\n";
        s += "<result name=\"response\" numFound=\"5\" start=\"0\">\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Wonderland</str>\n";
        s += "\n";
        s += "  <arr name=\"combined_artists\"><str>Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Who Needs Love (Like That) [The Love That Mix Version][*]</str><str>Wonderland</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">73</int>\n";
        s += "\n";
        s += "  <str name=\"key\">media:73</str>\n";
        s += "  <str name=\"label\">Mute</str>\n";
        s += "  <str name=\"objecttype\">media</str>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Erasure, Clarke, Vince</str></arr>\n";
        s += "\n";
        s += "  <arr name=\"tracktitle\"><str>Who Needs Love (Like That) [The Love That Mix Version][*]</str></arr>\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Wonderland</str>\n";
        s += "  <arr name=\"combined_artists\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Love Is a Loser</str><str>Wonderland</str></arr>\n";
        s += "\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">70</int>\n";
        s += "  <str name=\"key\">media:70</str>\n";
        s += "  <str name=\"label\">Mute</str>\n";
        s += "\n";
        s += "  <str name=\"objecttype\">media</str>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Love Is a Loser</str></arr>\n";
        s += " </doc>\n";
        s += "\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Wonderland</str>\n";
        s += "  <arr name=\"combined_artists\"><str>Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Who Needs Love (Like That)</str><str>Wonderland</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">71</int>\n";
        s += "  <str name=\"key\">media:71</str>\n";
        s += "  <str name=\"label\">Mute</str>\n";
        s += "  <str name=\"objecttype\">media</str>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Who Needs Love (Like That)</str></arr>\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Wonderland</str>\n";
        s += "\n";
        s += "  <arr name=\"bundleartist\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str>\n";
        s += "\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>\n";
        s += "          \n";
        s += "        </str><str>Wonderland</str><str>Senseless</str>\n";
        s += "  <str>Say What</str><str>Heavenly Action</str><str>Oh l'Amour</str><str>Love Is a Loser</str>\n";
        s += "\n";
        s += "  <str>Who Needs Love (Like That)</str><str>March on Down the Line</str><str>Who Needs Love (Like That) [The Love That Mix Version][*]</str><str>Oh l'Amour [The Funky Sisters Remix][*]</str>\n";
        s += "  <str>My Heart....So Blue</str><str>Reunion</str><str>Cry So Easy</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">12</int>\n";
        s += "  <str name=\"key\">bundle:12</str>\n";
        s += "  <str name=\"label\">Mute</str>\n";
        s += "  <str name=\"objecttype\">bundle</str>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "\n";
        s += "  <str>Bell, Andy [1], Erasure</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Senseless</str><str>Say What</str><str>Heavenly Action</str>\n";
        s += "  <str>Oh l'Amour</str><str>Love Is a Loser</str><str>Who Needs Love (Like That)</str><str>March on Down the Line</str>\n";
        s += "  <str>Who Needs Love (Like That) [The Love That Mix Version][*]</str><str>Oh l'Amour [The Funky Sisters Remix][*]</str><str>My Heart....So Blue</str><str>Reunion</str>\n";
        s += "\n";
        s += "  <str>Cry So Easy</str></arr>\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Wonderland</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "\n";
        s += "  <arr name=\"combined_artists\"><str>Erasure</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "\n";
        s += "  <str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Wonderland</str><str>\n";
        s += "          \n";
        s += "        </str><str>Senseless</str>\n";
        s += "  <str>Say What</str><str>Heavenly Action</str><str>Oh l'Amour</str><str>Love Is a Loser</str>\n";
        s += "\n";
        s += "  <str>Who Needs Love (Like That)</str><str>March on Down the Line</str><str>Who Needs Love (Like That) [The Love That Mix Version][*]</str><str>Oh l'Amour [The Funky Sisters Remix][*]</str>\n";
        s += "  <str>My Heart....So Blue</str><str>Reunion</str><str>Cry So Easy</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">12</int>\n";
        s += "  <str name=\"key\">album:12</str>\n";
        s += "  <str name=\"label\">Mute</str>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Erasure</str></arr>\n";
        s += "\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "\n";
        s += "  <str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str><str>Erasure, Clarke, Vince</str><str>Bell, Andy [1], Erasure, Clarke, Vince</str>\n";
        s += "  <str>Bell, Andy [1], Erasure</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Senseless</str><str>Say What</str><str>Heavenly Action</str>\n";
        s += "  <str>Oh l'Amour</str><str>Love Is a Loser</str><str>Who Needs Love (Like That)</str><str>March on Down the Line</str>\n";
        s += "\n";
        s += "  <str>Who Needs Love (Like That) [The Love That Mix Version][*]</str><str>Oh l'Amour [The Funky Sisters Remix][*]</str><str>My Heart....So Blue</str><str>Reunion</str>\n";
        s += "  <str>Cry So Easy</str></arr>\n";
        s += " </doc>\n";
        s += "</result>\n";
        s += "</response>\n";
        s += "\n";
        TRACK_TEST = s;
    }
    
    final static String ALBUM_TEST;
    static {
        String s = "";
        s += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        s += "<response>\n";
        s += "\n";
        s += "<lst name=\"responseHeader\">\n";
        s += " <int name=\"status\">0</int>\n";
        s += " <int name=\"QTime\">0</int>\n";
        s += " <lst name=\"params\">\n";
        s += "  <str name=\"rows\">10</str>\n";
        s += "  <str name=\"start\">0</str>\n";
        s += "\n";
        s += "  <str name=\"indent\">on</str>\n";
        s += "  <str name=\"q\">objecttype:album:love</str>\n";
        s += "  <str name=\"version\">2.2</str>\n";
        s += " </lst>\n";
        s += "</lst>\n";
        s += "<result name=\"response\" numFound=\"6\" start=\"0\">\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Above the Clouds</str>\n";
        s += "\n";
        s += "  <arr name=\"bundleartist\"><str>Whitehead, A., Wendell, Smith, J., Smith, Duke, George, Koz, Dave, Tisdale, Wayman, Brecker, Michael, White, Simpson, Brian, Simpson, Loeb, Chuck, Whalum, Kirk</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Brian Simpson</str><str>Whitehead, A., Wendell, Smith, J., Smith, Duke, George, Koz, Dave, Tisdale, Wayman, Brecker, Michael, White, Simpson, Brian, Simpson, Loeb, Chuck, Whalum, Kirk</str><str>Simpson, Brian, Simpson</str>\n";
        s += "  <str>Simpson, Brian, Simpson</str><str>Simpson, Brian, Simpson</str><str>Wendell, Simpson, Brian</str><str>Koz, Dave, Tisdale, Wayman, Simpson, Brian, Simpson</str>\n";
        s += "\n";
        s += "  <str>Whitehead, A., Brecker, Michael, Smith, J., Simpson, Brian, Simpson</str><str>Simpson, Brian, Simpson, Whalum, Kirk</str><str>Wendell, Simpson, Brian</str><str>Simpson, Brian, Simpson</str>\n";
        s += "  <str>Wendell, Duke, George, Simpson, Brian, Simpson</str><str>White, Smith, Simpson, Brian, Simpson, Loeb, Chuck</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Above the Clouds</str><str>\n";
        s += "          \n";
        s += "        </str><str>One More Time</str>\n";
        s += "  <str>Let's Get Close</str><str>Memories of You</str><str>Bali</str><str>Fiona's Song</str>\n";
        s += "\n";
        s += "  <str>That's Right</str><str>Juicy</str><str>Last Kiss</str><str>What Cha Gonna Do?</str>\n";
        s += "  <str>Above the Clouds</str><str>From the Hip</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Jazz</str></arr>\n";
        s += "\n";
        s += "  <int name=\"id\">69</int>\n";
        s += "  <str name=\"key\">album:69</str>\n";
        s += "  <str name=\"label\">Rendezvous (Red)</str>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Brian Simpson</str></arr>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Simpson, Brian, Simpson</str><str>Simpson, Brian, Simpson</str><str>Simpson, Brian, Simpson</str>\n";
        s += "  <str>Wendell, Simpson, Brian</str><str>Koz, Dave, Tisdale, Wayman, Simpson, Brian, Simpson</str><str>Whitehead, A., Brecker, Michael, Smith, J., Simpson, Brian, Simpson</str><str>Simpson, Brian, Simpson, Whalum, Kirk</str>\n";
        s += "  <str>Wendell, Simpson, Brian</str><str>Simpson, Brian, Simpson</str><str>Wendell, Duke, George, Simpson, Brian, Simpson</str><str>White, Smith, Simpson, Brian, Simpson, Loeb, Chuck</str></arr>\n";
        s += "\n";
        s += "  <arr name=\"tracktitle\"><str>One More Time</str><str>Let's Get Close</str><str>Memories of You</str>\n";
        s += "  <str>Bali</str><str>Fiona's Song</str><str>That's Right</str><str>Juicy</str>\n";
        s += "  <str>Last Kiss</str><str>What Cha Gonna Do?</str><str>Above the Clouds</str><str>From the Hip</str></arr>\n";
        s += "\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">One Cello, One World</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Chen, Chi, Lee, Teena</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Chi Chen</str><str>Chen, Chi, Lee, Teena</str><str>Chen, Chi</str>\n";
        s += "\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi, Lee, Teena</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi, Lee, Teena</str><str>Chen, Chi</str><str>Chen, Chi</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>One Cello, One World</str><str>\n";
        s += "          \n";
        s += "        </str><str>Moonlight and the Sea</str>\n";
        s += "\n";
        s += "  <str>Introduction</str><str>Introduction</str><str>Two Themes: Tale of a Small Town/You and I</str><str>Introduction</str>\n";
        s += "  <str>Green Island Seranade</str><str>River Separates Us</str><str>Hues of Twilight</str><str>Introduction</str>\n";
        s += "  <str>Introduction</str><str>Introduction</str><str>Introduction</str><str>Jasmine</str>\n";
        s += "\n";
        s += "  <str>Introduction</str><str>Introduction</str><str>Introduction</str><str>Moon Themes: The Moon Speaks for My Heart/Moon Over West Pavilion</str>\n";
        s += "  <str>Spring Fantasy: Azalea/Green Mountain/Rain Drops</str><str>Evening Fragrance</str><str>Moon Over Monterey Bay</str><str>Lingering Scent of Tea</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "\n";
        s += "  <arr name=\"genre\"><str>World</str></arr>\n";
        s += "  <int name=\"id\">70</int>\n";
        s += "  <str name=\"key\">album:70</str>\n";
        s += "  <str name=\"label\"/>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Chi Chen</str></arr>\n";
        s += "\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi, Lee, Teena</str><str>Chen, Chi</str>\n";
        s += "\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str>\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi</str><str>Chen, Chi, Lee, Teena</str>\n";
        s += "\n";
        s += "  <str>Chen, Chi</str><str>Chen, Chi</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Moonlight and the Sea</str><str>Introduction</str><str>Introduction</str>\n";
        s += "  <str>Two Themes: Tale of a Small Town/You and I</str><str>Introduction</str><str>Green Island Seranade</str><str>River Separates Us</str>\n";
        s += "  <str>Hues of Twilight</str><str>Introduction</str><str>Introduction</str><str>Introduction</str>\n";
        s += "\n";
        s += "  <str>Introduction</str><str>Jasmine</str><str>Introduction</str><str>Introduction</str>\n";
        s += "  <str>Introduction</str><str>Moon Themes: The Moon Speaks for My Heart/Moon Over West Pavilion</str><str>Spring Fantasy: Azalea/Green Mountain/Rain Drops</str><str>Evening Fragrance</str>\n";
        s += "  <str>Moon Over Monterey Bay</str><str>Lingering Scent of Tea</str></arr>\n";
        s += " </doc>\n";
        s += "\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Mass Destruction</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Nas, Jungle [1], Nashawn, G Wiz</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Nashawn</str><str>Nas, Jungle [1], Nashawn, G Wiz</str><str>Nashawn</str>\n";
        s += "\n";
        s += "  <str>Nashawn</str><str>Nashawn</str><str>Nashawn</str><str>Nashawn</str>\n";
        s += "  <str>Jungle [1], Nashawn</str><str>Nashawn</str><str>Nashawn</str><str>Nashawn</str>\n";
        s += "  <str>Nashawn</str><str>Nashawn</str><str>Nashawn</str><str>Jungle [1], Nashawn, G Wiz</str>\n";
        s += "\n";
        s += "  <str>Nashawn</str><str>Nashawn</str><str>Nashawn</str><str>Nas, Nashawn</str>\n";
        s += "  <str>Nashawn</str><str>Nas, Nashawn</str><str>Nashawn</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Mass Destruction</str><str>\n";
        s += "          \n";
        s += "        </str><str>My Style</str>\n";
        s += "\n";
        s += "  <str>Slow It Down</str><str>Bring It</str><str>Follow Me</str><str>It's True</str>\n";
        s += "  <str>Somebody Gotta Die</str><str>Car Lot</str><str>In Jail</str><str>Number 1</str>\n";
        s += "  <str>Understand</str><str>Fait Ball</str><str>Intro</str><str>All Summer Long</str>\n";
        s += "\n";
        s += "  <str>Huned</str><str>Rat Ass N*gg*Z</str><str>That Money</str><str>Take a Picture</str>\n";
        s += "  <str>We Gittin It</str><str>Bossed Up</str><str>Hustlin</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "\n";
        s += "  <arr name=\"genre\"><str>Rap</str></arr>\n";
        s += "  <int name=\"id\">71</int>\n";
        s += "  <str name=\"key\">album:71</str>\n";
        s += "  <str name=\"label\">Megabucks Ent.</str>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Nashawn</str></arr>\n";
        s += "\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Nashawn</str><str>Nashawn</str><str>Nashawn</str>\n";
        s += "  <str>Nashawn</str><str>Nashawn</str><str>Jungle [1], Nashawn</str><str>Nashawn</str>\n";
        s += "\n";
        s += "  <str>Nashawn</str><str>Nashawn</str><str>Nashawn</str><str>Nashawn</str>\n";
        s += "  <str>Nashawn</str><str>Jungle [1], Nashawn, G Wiz</str><str>Nashawn</str><str>Nashawn</str>\n";
        s += "  <str>Nashawn</str><str>Nas, Nashawn</str><str>Nashawn</str><str>Nas, Nashawn</str>\n";
        s += "\n";
        s += "  <str>Nashawn</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>My Style</str><str>Slow It Down</str><str>Bring It</str>\n";
        s += "  <str>Follow Me</str><str>It's True</str><str>Somebody Gotta Die</str><str>Car Lot</str>\n";
        s += "  <str>In Jail</str><str>Number 1</str><str>Understand</str><str>Fait Ball</str>\n";
        s += "\n";
        s += "  <str>Intro</str><str>All Summer Long</str><str>Huned</str><str>Rat Ass N*gg*Z</str>\n";
        s += "  <str>That Money</str><str>Take a Picture</str><str>We Gittin It</str><str>Bossed Up</str>\n";
        s += "  <str>Hustlin</str></arr>\n";
        s += " </doc>\n";
        s += "\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Vitus Dance</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Bingham, Christopher, Gaia Consort</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str></arr>\n";
        s += "\n";
        s += "  <arr name=\"combined_titles\"><str>Vitus Dance</str><str>\n";
        s += "          \n";
        s += "        </str><str>Vitus Dance</str>\n";
        s += "  <str>Turtles All the Way Down</str><str>Face in the Clouds</str><str>Oracle</str><str>Dirty Little Secret</str>\n";
        s += "  <str>Perils of Poly</str><str>Green</str><str>Only Now</str><str>Heather in the Mead</str>\n";
        s += "\n";
        s += "  <str>Twilight Calling</str><str>Mercy</str><str>Goodnight</str><str>All We've Got</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Rock</str></arr>\n";
        s += "  <int name=\"id\">72</int>\n";
        s += "\n";
        s += "  <str name=\"key\">album:72</str>\n";
        s += "  <str name=\"label\">Suddenly Naked Arts Collective</str>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Gaia Consort</str></arr>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "\n";
        s += "  <arr name=\"trackartist\"><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str>\n";
        s += "\n";
        s += "  <str>Bingham, Christopher, Gaia Consort</str><str>Bingham, Christopher, Gaia Consort</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Vitus Dance</str><str>Turtles All the Way Down</str><str>Face in the Clouds</str>\n";
        s += "  <str>Oracle</str><str>Dirty Little Secret</str><str>Perils of Poly</str><str>Green</str>\n";
        s += "  <str>Only Now</str><str>Heather in the Mead</str><str>Twilight Calling</str><str>Mercy</str>\n";
        s += "\n";
        s += "  <str>Goodnight</str><str>All We've Got</str></arr>\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Love Gonna Conquer Evil</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Natural Black, Davey, N., Corsdale, P., Firehouse Crew, Softly, M., Madden, D., Dodd, C., Murray, B., Chin, M.</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "\n";
        s += "  <arr name=\"combined_artists\"><str>Natural Black</str><str>Natural Black, Davey, N., Corsdale, P., Firehouse Crew, Softly, M., Madden, D., Dodd, C., Murray, B., Chin, M.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str>\n";
        s += "  <str>Natural Black, Softly, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Corsdale, P., Softly, M., Madden, D., Murray, B.</str>\n";
        s += "  <str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M., Dodd, C.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str>\n";
        s += "\n";
        s += "  <str>Natural Black, Softly, M., Dodd, C.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str>\n";
        s += "  <str>Natural Black, Davey, N., Softly, M., Murray, B., Chin, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Love Gonna Conquer Evil</str><str>\n";
        s += "          \n";
        s += "        </str><str>Lets Sing and Shout</str>\n";
        s += "  <str>Love Rastafari</str><str>Let Jah Jah Love Abide</str><str>Shame Face</str><str>There Is a Place</str>\n";
        s += "\n";
        s += "  <str>Cry for the People</str><str>Never Leave You Lonely</str><str>Dont Paint the Wrong Picture</str><str>Out of the Pit of Hell</str>\n";
        s += "  <str>No Cry Cry Smile</str><str>In Need of Something</str><str>I Won't Forget</str><str>How Could You</str>\n";
        s += "  <str>Rather Be Your Friend</str><str>You Should Take Advice</str></arr>\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Reggae</str></arr>\n";
        s += "  <int name=\"id\">73</int>\n";
        s += "  <str name=\"key\">album:73</str>\n";
        s += "  <str name=\"label\">Cousins</str>\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "\n";
        s += "  <arr name=\"primaryartist\"><str>Natural Black</str></arr>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str>\n";
        s += "  <str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Corsdale, P., Softly, M., Madden, D., Murray, B.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M., Dodd, C.</str>\n";
        s += "\n";
        s += "  <str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str><str>Natural Black, Softly, M., Dodd, C.</str><str>Natural Black, Firehouse Crew, Softly, M., Murray, B.</str>\n";
        s += "  <str>Natural Black, Softly, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str><str>Natural Black, Davey, N., Softly, M., Murray, B., Chin, M.</str><str>Natural Black, Softly, M., Firehouse Crew, Murray, B.</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Lets Sing and Shout</str><str>Love Rastafari</str><str>Let Jah Jah Love Abide</str>\n";
        s += "\n";
        s += "  <str>Shame Face</str><str>There Is a Place</str><str>Cry for the People</str><str>Never Leave You Lonely</str>\n";
        s += "  <str>Dont Paint the Wrong Picture</str><str>Out of the Pit of Hell</str><str>No Cry Cry Smile</str><str>In Need of Something</str>\n";
        s += "  <str>I Won't Forget</str><str>How Could You</str><str>Rather Be Your Friend</str><str>You Should Take Advice</str></arr>\n";
        s += "\n";
        s += " </doc>\n";
        s += " <doc>\n";
        s += "  <str name=\"albumtitle\">Inna De Yard</str>\n";
        s += "  <arr name=\"bundleartist\"><str>Kiddus I</str></arr>\n";
        s += "  <arr name=\"bundletitle\"><str>\n";
        s += "          \n";
        s += "        </str></arr>\n";
        s += "  <arr name=\"combined_artists\"><str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str>\n";
        s += "\n";
        s += "  <str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str>\n";
        s += "  <str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str>\n";
        s += "  <str>Kiddus I</str></arr>\n";
        s += "  <arr name=\"combined_titles\"><str>Inna De Yard</str><str>\n";
        s += "\n";
        s += "          \n";
        s += "        </str><str>Where Are You Going</str>\n";
        s += "  <str>Troubled Time [Winter Version]</str><str>No Salvation Until</str><str>Take Good Care of Me</str><str>Troubled Time [Summer Version]</str>\n";
        s += "  <str>Prayer</str><str>Reached Their Peaks</str><str>Economical Woes</str><str>Better Equity</str>\n";
        s += "  <str>World Should Be a Better Place (For Children to Play)</str></arr>\n";
        s += "\n";
        s += "  <bool name=\"explicitlyrics\">false</bool>\n";
        s += "  <str name=\"explicitlyrics_spa\">false</str>\n";
        s += "  <arr name=\"genre\"><str>Reggae</str></arr>\n";
        s += "  <int name=\"id\">74</int>\n";
        s += "  <str name=\"key\">album:74</str>\n";
        s += "  <str name=\"label\">Makasound</str>\n";
        s += "\n";
        s += "  <str name=\"objecttype\">album</str>\n";
        s += "  <arr name=\"primaryartist\"><str>Kiddus I</str></arr>\n";
        s += "  <str name=\"provider\">AMG</str>\n";
        s += "  <arr name=\"territory\"><str>US</str><str>ES</str></arr>\n";
        s += "  <arr name=\"trackartist\"><str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str>\n";
        s += "\n";
        s += "  <str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str>\n";
        s += "  <str>Kiddus I</str><str>Kiddus I</str><str>Kiddus I</str></arr>\n";
        s += "  <arr name=\"tracktitle\"><str>Where Are You Going</str><str>Troubled Time [Winter Version]</str><str>No Salvation Until</str>\n";
        s += "  <str>Take Good Care of Me</str><str>Troubled Time [Summer Version]</str><str>Prayer</str><str>Reached Their Peaks</str>\n";
        s += "\n";
        s += "  <str>Economical Woes</str><str>Better Equity</str><str>World Should Be a Better Place (For Children to Play)</str></arr>\n";
        s += " </doc>\n";
        s += "</result>\n";
        s += "</response>\n";
        s += "\n";
        ALBUM_TEST = s;
    }
       
}
