package com.limegroup.bittorrent.disk;

import java.io.IOException;
import java.util.List;
import java.util.Set;

import org.limewire.collection.BitField;
import org.limewire.collection.NECallable;

import com.limegroup.bittorrent.BTInterval;
import com.limegroup.bittorrent.BTPiece;
import com.limegroup.bittorrent.PieceReadListener;
import com.limegroup.bittorrent.handshaking.piecestrategy.PieceStrategy;
import com.limegroup.gnutella.downloader.serial.BTDiskManagerMemento;

/**
 * A facility that manages access to the collection of files 
 * belonging to a torrent and keeps track of which ranges are
 * verified, missing, requested, verified.
 */
public interface TorrentDiskManager {

	/**
	 * Opens this TorrentDiskManager.  MUST be called before anything
	 * else.
	 */
	public void open(final DiskManagerListener torrent) throws IOException;

	/**
	 * closes all file descriptors used by this.
	 */
	public void close();

	/**
	 * determines whether the files for this torrent are open.
	 */
	public boolean isOpen();

	/**
	 * Requests that a write be performed for a block that will be
	 * generated by the provided callable.
	 */
	public void writeBlock(NECallable<BTPiece> factory);

	/**
	 * Requests that a piece be read from disk
	 * @param in the <tt>BTInterval</tt> representing the Piece
	 * @param listener the <tt>PieceReadListener</tt> to notify once the read
	 * completes
	 * @throws IOException if something goes wrong
	 */
	public void requestPieceRead(BTInterval in, PieceReadListener listener);
	
	/**
	 * @return true if the provided block number is verified.
	 */
	public boolean hasBlock(int block);

	/**
	 * @return true if this is currently verifying any data found on disk
	 */
	public boolean isVerifying();

	/**
	 * @return true if the all the blocks have been written and verified
	 */
	public boolean isComplete();

	/**
	 * Returns an array of BTIntervals selected using the given piece strategy.
	 * 
     * @param bs the <tt>BitField</tt> of available ranges to choose from
     * @param exclude the set of ranges that the connection is already about to request
     * @param pieceStrategy the piece strategy to select the intervals with.
     * @return a BTInterval that should be requested next.
	 */
	List<BTInterval> lease(BitField bs, Set<BTInterval> exclude, PieceStrategy pieceStrategy);
	
	/**
	 * Returns up to 16k of a btInterval selected using the given piece strategy. 
	 * If not pieceStrategy is included a default strategy will be selected.
	 * 
	 * @param bs the <tt>BitField</tt> of available ranges to choose from
	 * @param exclude the set of ranges that the connection is already about to request
	 * @param pieceStrategy the piece strategy to select the intervals with. Can be null.
	 * @return a BTInterval that should be requested next.
	 */
	public BTInterval leaseBTInterval(BitField bs, Set<BTInterval> exclude, PieceStrategy pieceStrategy);

	/**
	 * Removes an interval from the internal list of already requested intervals.
	 * <p>
	 * Note that during end game, several connections may be requesting the same interval
	 * and as one of them fails that interval will no longer be considered requested.
	 * That's ok as it will only result in that interval requested again. (See
	 * http://wiki.theory.org/BitTorrentSpecification#End_Game)
	 */
	public void releaseInterval(BTInterval in);

	/**
	 * @return returns an array of byte where the i'th byte is 1 if we have
	 *         written and verified the i'th piece of the torrent and 0
	 *         otherwise
	 */
	public byte[] createBitField();

	/**
	 * @return number of bytes written and verified
	 */
	public long getVerifiedBlockSize();

	/**
	 * @return number of bytes written
	 */
	public long getBlockSize();

	/**
	 * @return number of bytes corrupted
	 */
	public long getNumCorruptedBytes();

	/**
	 * @return true if the remote host has any pieces we miss
	 */
	public boolean containsAnyWeMiss(BitField other);
	
	/**
	 * @return the number of pieces that this has verified
	 * and are not set in the provided <tt>BitField</tt>
	 */
	public int getNumMissing(BitField other);
	
	/**
	 * @return the amount of data pending write
	 */
	public int getAmountPending();
	
	/**
	 * @return a memento describing this.
	 */
	public BTDiskManagerMemento toMemento();
    
    /**
     * @return the last offset inside the torrent file system that has been 
     * successfully verified.
     */
    public long getLastVerifiedOffset();

    /**
     * Shrinks a lease from the old intrval to the new one.
     * 
     * @param oldInterval old interval to shrink
     * @param newInterval new interval to maintain leased
     */
    public void renewLease(List<BTInterval> oldInterval, List<BTInterval> newInterval);

}