package org.limewire.ui.swing.components;

import java.awt.Component;

import javax.swing.JLabel;
import javax.swing.JPanel;

import net.miginfocom.swing.MigLayout;

/**
 * A simple component that can be used to inset a text label with an arbitrary number of components.
 * 
 * <p>Components are loaded in order in the places of the string marked by {c}.
 * 
 * <p>Example String:
 * <p>"the label generated by this string will be {c} embedded with its first component at the point with the symbol"
 *  
 */
public class EmbeddedComponentLabel extends JPanel {

    public EmbeddedComponentLabel(String message, Component... components) {
     
        super(new MigLayout("insets 0, gap 0"));
        
        setOpaque(false);
        
        String[] labelParts = message.split("\\{c\\}");
        
        int i = 0;
        for ( String part : labelParts ) {
            add(new JLabel(part));
            if (i < components.length && components[i] != null) {
                add(components[i]);
                i++;
            }
        }
        
    }
    
}
