package com.limegroup.gnutella;

import java.io.IOException;

/**
 * This interface is implemented by ManagedConnection (for routing PingReplies)
 * and by other singleton classes for implementing different strategies for
 * handling a reply to a PingRequest generated by the computer on which this
 * code is running.  PingReplyHandlers are not responsible for handling routing;
 * they should examine the contents of the PingReply as necessary and handle the
 * message accordingly
 *
 * @author Ron Vogl
 */
public interface PingReplyHandler
    extends ReplyHandler
{
    /**
     * Handle the PingReply, failing silently
     */
    void handlePingReply(PingReply pingReply,
                         ManagedConnection receivingConnection,
                         MessageRouter router,
                         ActivityCallback callback);
}
