package com.limegroup.gnutella;

import java.io.IOException;

/**
 * This interface is implemented by ManagedConnection (for routing PushRequest)
 * and by other singleton classes for implementing different strategies for
 * handling a reply to a QueryReply generated by the computer on which this
 * code is running.  PushRequestHandlers are not responsible for handling
 * routing; they should examine the contents of the PushRequest as necessary and
 * handle the message accordingly.
 *
 * @author Ron Vogl
 */
public interface PushRequestHandler
    extends ReplyHandler
{
    /**
     * Handle the PushRequest, failing silently
     */
    void handlePushRequest(PushRequest pushRequest,
                           MessageRouter router,
                           ActivityCallback callback);
}
