package com.limegroup.gnutella;

import java.net.*;
import java.io.IOException;
import java.util.*;

/**
 *This data structure keeps track of replies from servants.
 *When a servant replies to a query (meaning she has some data)
 *then we want to store some information about her, in every client on the way.
 *First - The GUID of the reply that was send
 *Second - the connection from which this reply has come in
 *Third - The GUID generated by  host from which this reply has originated
 *Note the third compenent can be obtained from the last 16 bytes 
 *of a standard reply package
 */

public class PushRouteTable{

    //Note when one servant is sending a push request it needs a combination
    //of field one and three to determine the second field.
    // thus in the hashtable I will be storing a concatination of 1+3
        
    private Map hasher ;
    
    public PushRouteTable(int size){
	hasher = new ForgetfulHashMap(size);
    }
    
    /**
     *When a push request comes we want to be able to send out the
     *reques to only the port where the reply came from. Thus we need to know the GUID
     * of the reply and the GUID that was generated my the servant that has the data we need
     *(also the final destination of this request)
     *Thus we use look up based on the Guid and DestinationGuid and return a connection.
     */
    public synchronized Connection get(Message m){
	PushRequest mess = (PushRequest)m;
	String key = new String(mess.getClientGUID());
	//System.out.println("Sumeet:key is " + key);
	return (Connection)hasher.get(key);
    }
    
    /**
     *Overloaded version of get. Takes a String = GUID+CliendID
     * returns the corresponding connection
     */
    public synchronized Connection get(String key){
	return (Connection)hasher.get(key);
    }


    /**This function is used to store a which connection a particular message came  from
     *It will be used when we have a push request and we want to to find out 
     *which connection to send out a push requst on. See get
     */
    public synchronized void put(Connection c, Message m){
	QueryReply  mes = (QueryReply)m;
	String key  = new String(mes.getClientGUID());
	//System.out.println("Sumeet: putting hash table key" + key);
	hasher.put(key,c);
    }
    
    public synchronized String toString() {
	StringBuffer buf=new StringBuffer("\n");
	Iterator iter=hasher.keySet().iterator();
	while (iter.hasNext()) {
	    String routeKey = (String) iter.next();
	    Connection conn=get(routeKey);
	    Assert.that(conn!=null);
	    buf.append(routeKey);
	    buf.append(" -> ");
	    buf.append(conn.toString());
	    buf.append("\n");
	}
	return buf.toString();
    }    
}

