package com.limegroup.gnutella;

import java.io.IOException;

/**
 * This interface is implemented by ManagedConnection (for routing QueryReplies)
 * and by other singleton classes for implementing different strategies for
 * handling a reply to a QueryRequest generated by the computer on which this
 * code is running.  QueryReplyHandlers are not responsible for handling
 * routing; they should examine the contents of the QueryReply as necessary and
 * handle the message accordingly
 *
 * @author Ron Vogl
 */
public interface QueryReplyHandler
    extends ReplyHandler
{
    /**
     * Handle the QueryReply, failing silently
     */
    void handleQueryReply(QueryReply queryReply,
                          ManagedConnection receivingConnection,
                          MessageRouter router,
                          ActivityCallback callback);
}
