
package com.limegroup.gnutella.bootstrap;

import java.text.ParseException;

/**
 * The list of default GWebCache urls, used the first time LimeWire starts, or
 * if the gnutella.net file is accidentally deleted.  Entries in the list will
 * eventually be replaced by URLs discovered during urlfile=1 requests.  Order
 * does not matter.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED FROM MAKE_DEFAULT.PY.
 */
public class DefaultBootstrapServers {
    /**
     * Adds all the default servers to bman. 
     */
    public static void addDefaults(BootstrapServerManager bman) {
        for (int i=0; i<urls.length; i++) {
            try {
                BootstrapServer server=new BootstrapServer(urls[i]);
                bman.addBootstrapServer(server);
            } catch (ParseException ignore) {
            }                
        }
    }

    //These should NOT be URL encoded.
    static String[] urls=new String[] {
        "http://128.211.214.246/gcache.php",
        "http://bobsmith.kicks-ass.org/gwebcache/gcache.php",
        "http://dlaikar.de/gcache-mac/gcache.php",
        "http://dlaikar.de/gcache/gcache.php",
        "http://dlaikar.de/gcache2/gcache.php",
        "http://firebird.shacknet.nu:8888/cash.php",
        "http://foxy1.cjb.net/cgi-bin/gcache.cgi",
        "http://foxy1.cjb.net/gwcii.php",
        "http://g2cache.theg2.net/gwcache/lynnx.asp",
        "http://g2wc.markushenn.de/gwcii.php",
        "http://galvatron.dyndns.org:59009/gwcache",
        "http://grupaprojektor.host.sk/gcache.php",
        "http://gwc.awyeah.net/",
        "http://gwc.gwc.niet.net/gwc/gcache.cgi",
        "http://gwcii.julianfamily.org/gwcii.php",
        "http://gwebcache.bearshare.net/",
        "http://gwebcache.dnsalias.org/cgi-bin/perlgcache.cgi",
        "http://gwebcache.h45h.com/gwcii.php",
        "http://gwebcache1.limewire.com/gwebcache/cgi-bin/perlgcache.cgi",
        "http://gwebcache3.jonatkins.org.uk/perlgcache.cgi",
        "http://huithome.xs4all.nl/gwebcache/lynnx.aspx",
        "http://invalidsubdomain.toddenrentieren.net/gcache.php",
        "http://ipoh1.org/gwebcache/gwcii.php",
        "http://kunkie.europe.webmatrixhosting.net/lynnx.aspx",
        "http://mckeowbc.servebeer.com/gcache.php",
        "http://mikama.host.sk/gcache.php",
        "http://move.along.move.along.there.is.nothing.to.see.here.at.bishopston.net:3558/",
        "http://mute-net.sourceforge.net/cgi-bin/perlgcache.cgi",
        "http://paladin.teamunix.de/gwebcache/gwcii.php",
        "http://static.zabox.com/gwc/gwcii.php",
        "http://tv2knet.basm.be/gcache.php",
        "http://www.bearguru.com/gcache/gcache.asp",
        "http://www.blackfedora.com/gcache/perlgcache.cgi",
        "http://www.easwww.xolox.nl/gwebcache/default.asp",
        "http://www.easypublish.net/gwebcache/gcache.asp",
        "http://www.goeg.dk/Gnutella/gcache.php",
        "http://www.kinnee.net/cgi-bin/perlgcache.cgi",
        "http://www.pietroam.net/script/gnutella/phpgnucacheII/gwcii.php",
        "http://www.spiderplayer.net/gwebcache.aspx",
        "http://www.wtndrifters.com/gcache.php",
        "http://www.xolox.nl/gwebcache",
        "http://www.xolox.nl/gwebcache/default.asp"
    };
}
